### ISSUE TITLE
Comments not recognized?

### ISSUE THREAD

**Issue by chriddyp** [plotly/falcon-sql-client#417] opened 2018-04-13 15:05 UTC
Error report from a user:
>  I found the issue with the query. I’m seeing that the ‘#’ character typically used to define comments in MySQL is not supported. If I put it near the end of the query, the query executes, with no error, ignoring the line following the characters.

I haven't confirmed or tested this myself.

**Comment by n-riesco** [comment] 2018-04-13 17:25
Just tested Falcon v2.6 and comments with `#`, `--` and `\*  *\` work with the MySQL connector:

![image](https://user-images.githubusercontent.com/6199391/38749018-08f5dab0-3f48-11e8-9a8f-1b786a2d7389.png)

**Comment by n-riesco** [comment] 2018-06-05 16:52
Closing since it can't be reproduced and there hasn't been any recent activity.

**Closed by n-riesco** 2018-06-05 16:52 UTC
Labels: cannot reproduce
