### ISSUE TITLE
Building from Source on Mac

### ISSUE THREAD

**Issue by shannonlal** [plotly/falcon-sql-client#307] opened 2017-12-11 01:24 UTC
I am running into an issue trying to build the application from source on a mac.  Here is my current Mac environment details:

# Environment Variables
yarn: v1.3.2
node: v6.11.5
npm: 3.10.10
Mac Build: 10.13.1

I have tried building from master and branch 2.2-release and I am getting similar problems.  The following are the instructions I am using for building from source.   This was defined in issue #261: 

# Installation Instructions
```bash
$ yarn install
$ yarn run rebuild:modules:electron
$ rm -rf dist
$ yarn run build-headless
$ yarn start-headless
 ```

When I run the build command I get build warnings about missing modules (see below).  And then when I try to run I get two errors (see below) and it never starts. The first is about a missing module (which I assume is linked to the warnings) and the second is about a module version mismatch:

## Error 1: 
Error: Cannot find module "./build"

## Error 2: 
Error: Module version mismatch. Expected 48, got 54.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)

Any help would be greatly appreciated.  We are interested in using this tool at my company and I am personally interested in contributing to the project.  Any guidance or help would be greatly appreciated.

Thanks

## Build Warnings:

```bash
WARNING in ./node_modules/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/encoding/lib/iconv-loader.js
 @ ./node_modules/encoding/lib/encoding.js
 @ ./node_modules/node-fetch/lib/body.js
 @ ./node_modules/node-fetch/index.js
 @ ./backend/routes.js
 @ ./backend/main.development.js

WARNING in ./node_modules/ws/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/Release/bufferutil' in '/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/node_modules/ws/lib'
 @ ./node_modules/ws/lib/BufferUtil.js 8:19-57
 @ ./node_modules/ws/lib/Sender.js
 @ ./node_modules/ws/index.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/ws_connection.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/index.js
 @ ./node_modules/node-impala/lib/node-impala.js
 @ ./node_modules/node-impala/index.js
 @ ./backend/persistent/datastores/impala.js
 @ ./backend/persistent/datastores/Datastores.js
 @ ./backend/routes.js
 @ ./backend/main.development.js

WARNING in ./node_modules/ws/lib/Validation.js
Module not found: Error: Can't resolve '../build/Release/validation' in '/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/node_modules/ws/lib'
 @ ./node_modules/ws/lib/Validation.js 8:19-57
 @ ./node_modules/ws/lib/Receiver.js
 @ ./node_modules/ws/index.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/ws_connection.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/index.js
 @ ./node_modules/node-impala/lib/node-impala.js
 @ ./node_modules/node-impala/index.js
 @ ./backend/persistent/datastores/impala.js
 @ ./backend/persistent/datastores/Datastores.js
 @ ./backend/routes.js
 @ ./backend/main.development.js

WARNING in ./node_modules/ws/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/default/bufferutil' in '/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/node_modules/ws/lib'
 @ ./node_modules/ws/lib/BufferUtil.js 10:19-57
 @ ./node_modules/ws/lib/Sender.js
 @ ./node_modules/ws/index.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/ws_connection.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/index.js
 @ ./node_modules/node-impala/lib/node-impala.js
 @ ./node_modules/node-impala/index.js
 @ ./backend/persistent/datastores/impala.js
 @ ./backend/persistent/datastores/Datastores.js
 @ ./backend/routes.js
 @ ./backend/main.development.js

WARNING in ./node_modules/ws/lib/Validation.js
Module not found: Error: Can't resolve '../build/default/validation' in '/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/node_modules/ws/lib'
 @ ./node_modules/ws/lib/Validation.js 10:19-57
 @ ./node_modules/ws/lib/Receiver.js
 @ ./node_modules/ws/index.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/ws_connection.js
 @ ./node_modules/thrift/lib/nodejs/lib/thrift/index.js
 @ ./node_modules/node-impala/lib/node-impala.js
 @ ./node_modules/node-impala/index.js
 @ ./backend/persistent/datastores/impala.js
 @ ./backend/persistent/datastores/Datastores.js
 @ ./backend/routes.js
 @ ./backend/main.development.js
```
## Run Errors
```bash
yarn run v1.3.2
$ cross-env NODE_ENV=production node ./dist/headless-bundle.js
{ Error: Cannot find module "./build"
    at /Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:151:16226
    at Object.r.keys (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:151:16302)
    at t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:101)
    at Object.i.addProbe.t.fire (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:151:6471)
    at t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:101)
    at Object.t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:62154)
    at t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:101)
    at Object.<anonymous> (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:151:280)
    at t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:101)
    at /Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:451 code: 'MODULE_NOT_FOUND' }
Error: Module version mismatch. Expected 48, got 54.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.e.__esModule.default (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:152:1737661)
    at t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:101)
    at Object.<anonymous> (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:152:1737438)
    at t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:101)
    at Object.t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:130615)
    at t (/Users/shannonlal/Personel/Technology/plot.ly/falcon-sql-client/dist/headless-bundle.js:2:101)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by n-riesco** [comment] 2017-12-11 07:22
I'm marking this bug as `documentation` to remind me update https://github.com/plotly/falcon-sql-client/blob/master/CONTRIBUTING.md .

The build instructions depend on whether you want build the desktop or the web app. The issue you're seeing happens because `yarn run rebuild:modules:electron` builds the native modules against electron, but `yarn start-headless` starts the web app.

The instructions to build and start the desktop app are:
```
$ yarn install
$ yarn run rebuild:modules:electron
$ yarn run build
$ yarn start
```

And the instructions to build and start the web app (by default listening on http://localhost:9494) are on a fresh install:
```
$ yarn install
$ yarn run heroku-postbuild
$ yarn run start-headless
```

on a install previously used to build the desktop app
```
$ yarn run rebuild:modules:node
$ yarn run heroku-postbuild
$ yarn run start-headless
```

**Comment by shannonlal** [comment] 2017-12-11 10:58
Ok thanks for this.  This looks pretty easy so if you want I will update the documentation and send in a pull request for you.

Thanks again for the response

**Comment by shannonlal** [comment] 2017-12-11 13:30
I updated the CONTRIBUTING.md document to include your instructions and submitted a PR.  I also tested the instructions on my Mac and was able to get the environment build and running.  Thanks again for help it is greatly appreciated

**Comment by n-riesco** [comment] 2017-12-12 07:36
Closed via #308

**Closed by n-riesco** 2017-12-12 07:36 UTC
Labels: documentation

**Comment by pietersv** [comment] 2018-04-19 13:08
I was able to build and run Falcon SQL Client as an electron app locally with Node 6.12 following the instructions on the current `CONTRIBUTING.md` just fine.  However, I still see the exact messages for Error 1 and Error 2 above when running `yarn build` and `yarn start`.  But it does build and start.

**Comment by n-riesco** [comment] 2018-04-19 14:07
@pietersv `yarn start` assumes `yarn rebuild:modules:electron` has been run after `yarn install`.

how do you get Error 1?

**Comment by n-riesco** [comment] 2018-04-19 16:52
I looks like the cause is `dtrace-provider`. As a workaround, I'd remove `dtrace-provider` from `node_modules`. To be safe, after removing `dtrace-provider`, I'd rebuild the native modules and the bundles:
```
yarn rebuild:modules:electron
yarn build
yarn start
```

---

I've opened issue #421 to remove `dtrace-provider`.
